A=32
B=4

# arithmatic
print("A+B=", A+B)
print("A-B=", A-B)
print("A*B=", A*B)
print("A/B=", A/B)
print("A//B=", A//B)
print("A**B=", A**B)

# conditional operator
print("A>B=", A>B)
print("A<B=", A<B)
print("A==B=", A==B)
print("A!=B=", A!=B)
print("A>=B=", A>=B)
print("A<=B=", A<=B)


#logical operator
print(True and False)
print(True and True)
 

# Assignment 
a=32
print("A==B=", A==B)
print("A!=B=", A!=B)
print("A>=B=", A>=B)
print("A<=B=", A<=B)


#logical operator
print(True and False)
print(True and True)


# Assignment
a=32
print("A=", a)
a-=2
print(a)